"""
This file contains the MDP model that was used. These constants are 
used for both methods.
"""

states = [
    "CKD5",
    "A_CC",
    "A_Dialysis",
    "A_Transplant",
    "CC",
    "Dialysis",
    "Transplant",
    "Death",
    "Stroke",
    "Disability",
    "MI",
    "CHF",
    "A_Fistula",
    "A_OneMonth",
    "Fistula",
    "OneMonth",
    "AfterOneMonth",
    "Successful",
    "Stroke_D",
    "Disability_D",
    "MI_D",
    "CHF_D",
    "Stroke_DA",
    "Disability_DA",
    "MI_DA",
    "CHF_DA",
    "Stroke_T",
    "Disability_T",
    "MI_T",
    "CHF_T",
    "Stroke_F",
    "Disability_F",
    "MI_F",
    "CHF_F",
]

actions = {
    "CKD5": ["A_CC", "A_Dialysis", "A_Transplant"],
    "Dialysis": ["A_Fistula", "A_OneMonth"],
}

utilities = {
    "CC": 0.98,
    "Fistula": 0.85,
    "Death": 0.0,
    "OneMonth": 0.8,
    "AfterOneMonth": 0.8,
    "Successful": 0.95,
    "Disability": 0.35,
    "Disability_F": 0.35,
    "Disability_D": 0.35,
    "Disability_DA": 0.35,
    "Disability_T": 0.35,
    "CHF": 0.76,
    "CHF_F": 0.76,
    "CHF_D": 0.76,
    "CHF_DA": 0.76,
    "CHF_T": 0.76,
    "Stroke": 0.5,
    "Stroke_F": 0.5,
    "Stroke_D": 0.5,
    "Stroke_DA": 0.5,
    "Stroke_T": 0.5,
    "MI": 0.5,
    "MI_F": 0.5,
    "MI_D": 0.5,
    "MI_DA": 0.5,
    "MI_T": 0.5,
}

transitions = {
    # CC subtree
    "CC": [("Death", 0.09812), ("Stroke", 0.006), ("MI", 0.00792), ("CC", 0.88796)],
    "Stroke": [("Disability", 0.33), ("Death", 0.2), ("CC", 0.47)],
    "MI": [("Death", 0.08), ("CHF", 0.05), ("CC", 0.87)],
    "Disability": [("CC", 1.0)],
    "CHF": [("CC", 1)],
    # Transplant subtree
    "Transplant": [("Death", 0.012), ("Successful", 0.988)],
    "Successful": [
        ("Dialysis", 0.0051),
        ("MI_T", 0.0028),
        ("Death", 0.0031),
        ("Stroke_T", 0.003),
        ("Successful", 0.986),
    ],
    "Stroke_T": [("Disability_T", 0.33), ("Death", 0.2), ("Successful", 0.47)],
    "MI_T": [("CHF_T", 0.05), ("Death", 0.08), ("Successful", 0.87)],
    "CHF_T": [("Successful", 1.0)],
    "Disability_T": [("Successful", 1.0)],
    # Fistula subtree
    "Fistula": [
        ("Death", 0.0133),
        ("Stroke_F", 0.0115),
        ("Fistula", 0.9713),
        ("MI_F", 0.0039),
    ],
    "Stroke_F": [("Death", 0.55), ("Disability_F", 0.33), ("Fistula", 0.12)],
    "MI_F": [("Death", 0.08), ("CHF_F", 0.05), ("Fistula", 0.87)],
    "Disability_F": [("Fistula", 1.0)],
    "CHF_F": [("Fistula", 1.0)],
    # OneMonth subtree
    "OneMonth": [
        ("Stroke_D", 0.0115),
        ("Death", 0.0425),
        ("MI_D", 0.0039),
        ("AfterOneMonth", 0.9421),
    ],
    "Stroke_D": [("Disability_D", 0.33), ("Death", 0.492), ("AfterOneMonth", 0.178)],
    "MI_D": [("Death", 0.08), ("CHF_D", 0.05), ("AfterOneMonth", 0.87)],
    "Disability_D": [("AfterOneMonth", 1.0)],
    "CHF_D": [("AfterOneMonth", 1.0)],
    "AfterOneMonth": [
        ("AfterOneMonth", 0.9699),
        ("Stroke_DA", 0.0115),
        ("MI_DA", 0.0039),
        ("Death", 0.0147),
    ],
    "Stroke_DA": [("Death", 0.55), ("Disability_DA", 0.33), ("AfterOneMonth", 0.12)],
    "MI_DA": [("Death", 0.08), ("CHF", 0.05), ("AfterOneMonth", 0.87)],
    "CHF_DA": [("AfterOneMonth", 1.0)],
    "Disability_DA": [("AfterOneMonth", 1.0)],
}
